# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpTunnel < Formula
  desc "Tunnel 1Password CLI (op) commands over SSH"
  homepage "https://github.com/middlendian/op-tunnel"
  version "0.2.0"
  license "MIT"

  depends_on "1password-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.0/op-tunnel-0.2.0-darwin-amd64.tar.gz"
      sha256 "216f5c30c0f255d508e1d279e2ce3affe9d36e64d121fb58d3fa399e34b70f36"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.0/op-tunnel-0.2.0-darwin-arm64.tar.gz"
      sha256 "6afad9f2aaf90afd58c7a842eca4fe4bebbb188c20d530d698f18b6cfbbc1bde"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.0/op-tunnel-0.2.0-linux-amd64.tar.gz"
      sha256 "7daed07c140b8e97dfb38800f70b75ebaad57461321da52f4374af9d7233f95f"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.0/op-tunnel-0.2.0-linux-arm64.tar.gz"
      sha256 "13877d9ba76ee5afa39b271644b19c81206870866244a30624b8f9e442e2975c"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  def caveats
    <<~EOS
      Run op-tunnel-setup to complete configuration:
        op-tunnel-setup

      See https://github.com/middlendian/op-tunnel for full instructions.
    EOS
  end

  service do
    run [opt_bin/"op-tunnel-server"]
    keep_alive true
    log_path var/"log/op-tunnel-server.log"
    error_log_path var/"log/op-tunnel-server.log"
  end

  test do
    assert_predicate bin/"op-tunnel-server", :executable?
    assert_predicate bin/"op-tunnel-client", :executable?
  end
end
