# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpTunnel < Formula
  desc "Tunnel 1Password CLI (op) commands over SSH"
  homepage "https://github.com/middlendian/op-tunnel"
  version "0.2.1"
  license "MIT"

  depends_on "1password-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.1/op-tunnel-0.2.1-darwin-amd64.tar.gz"
      sha256 "2ffdef2bb1ebe38939afc0766c0d9d12c76e64dce51f044de61923641bf8f054"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.1/op-tunnel-0.2.1-darwin-arm64.tar.gz"
      sha256 "fe7c60638d0d696d4af0b968e959621604327bf17fce0969170d774ea44fcd7f"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.1/op-tunnel-0.2.1-linux-amd64.tar.gz"
      sha256 "4280f463f5c984966ef48754f169e391ef98db98b4ec79744dab3c3bbd85cf4e"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.1/op-tunnel-0.2.1-linux-arm64.tar.gz"
      sha256 "3d869ec5d29e1f88efe10403814f9157bc66ca60b7bb4c909423761e7b1ef82f"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  def caveats
    <<~EOS
      Run op-tunnel-setup to complete configuration:
        op-tunnel-setup

      See https://github.com/middlendian/op-tunnel for full instructions.
    EOS
  end

  service do
    run [opt_bin/"op-tunnel-server"]
    keep_alive true
    log_path var/"log/op-tunnel-server.log"
    error_log_path var/"log/op-tunnel-server.log"
  end

  test do
    assert_predicate bin/"op-tunnel-server", :executable?
    assert_predicate bin/"op-tunnel-client", :executable?
  end
end
