# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpTunnel < Formula
  desc "Tunnel 1Password CLI (op) commands over SSH"
  homepage "https://github.com/middlendian/op-tunnel"
  version "0.3.3"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.3.3/op-tunnel-0.3.3-darwin-amd64.tar.gz"
      sha256 "2fcca956171bc0f4301e394e84f8c60a05c84593f7afaf4459bbba586c11cbf0"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        bin.install "op-tunnel-doctor"
        bin.install "op-tunnel-keepalive"
        (share/"op-tunnel").install "dist/ssh.config.tmpl"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.3.3/op-tunnel-0.3.3-darwin-arm64.tar.gz"
      sha256 "6780be1f2d2daf39c77a3e350a6aef94ea3f18828a69fc68ce3e0e087b955019"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        bin.install "op-tunnel-doctor"
        bin.install "op-tunnel-keepalive"
        (share/"op-tunnel").install "dist/ssh.config.tmpl"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.3.3/op-tunnel-0.3.3-linux-amd64.tar.gz"
      sha256 "c57fbcb33bbb61116a9f342227fea9415871bfc5d4675f1303d650c875a5a3f3"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        bin.install "op-tunnel-doctor"
        bin.install "op-tunnel-keepalive"
        (share/"op-tunnel").install "dist/ssh.config.tmpl"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.3.3/op-tunnel-0.3.3-linux-arm64.tar.gz"
      sha256 "f8fd846af5830de31b8b900483e2ec5db92481e9267a1ab8b3012592bdcc4fa3"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        bin.install "op-tunnel-doctor"
        bin.install "op-tunnel-keepalive"
        (share/"op-tunnel").install "dist/ssh.config.tmpl"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  def caveats
    <<~EOS
      To complete setup, run:
        op-tunnel-setup && op-tunnel-doctor

      See https://github.com/middlendian/op-tunnel for full instructions.
    EOS
  end

  service do
    run [opt_bin/"op-tunnel-server"]
    keep_alive true
    log_path var/"log/op-tunnel-server.log"
    error_log_path var/"log/op-tunnel-server.log"
    environment_variables PATH: "#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  test do
    assert_predicate bin/"op-tunnel-server", :executable?
    assert_predicate bin/"op-tunnel-client", :executable?
    assert_predicate bin/"op-tunnel-doctor", :executable?
    assert_predicate bin/"op-tunnel-keepalive", :executable?
  end
end
