# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpTunnel < Formula
  desc "Tunnel 1Password CLI (op) commands over SSH"
  homepage "https://github.com/middlendian/op-tunnel"
  version "0.2.2"
  license "MIT"

  depends_on "1password-cli" => :cask

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.2/op-tunnel-0.2.2-darwin-amd64.tar.gz"
      sha256 "197d786a0ccd5f9642b4e47d4533b8b3e0e89b9c5ffcb3e9e3d84b54bf5e604a"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.2/op-tunnel-0.2.2-darwin-arm64.tar.gz"
      sha256 "2103d017b986799f6d63a72fe50c4fa6c084fc99a505caf3cd371c310eb1ab1a"

      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.2/op-tunnel-0.2.2-linux-amd64.tar.gz"
      sha256 "6a4475952735041a46f802e95164f28bb6350d5567bd44140a82810bb8145598"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/middlendian/op-tunnel/releases/download/v0.2.2/op-tunnel-0.2.2-linux-arm64.tar.gz"
      sha256 "c6a436ffea044a89e11348fa12abc4403ba3c421867622d75ed452e3d13b144e"
      define_method(:install) do
        bin.install "op-tunnel-server"
        bin.install "op-tunnel-client"
        (share/"op-tunnel").install "dist/op-tunnel-sshd.conf", "dist/ssh.config"
        bin.install "dist/op-tunnel-setup"
      end
    end
  end

  def caveats
    <<~EOS
      Run op-tunnel-setup to complete configuration:
        op-tunnel-setup

      See https://github.com/middlendian/op-tunnel for full instructions.
    EOS
  end

  service do
    run [opt_bin/"op-tunnel-server"]
    keep_alive true
    log_path var/"log/op-tunnel-server.log"
    error_log_path var/"log/op-tunnel-server.log"
  end

  test do
    assert_predicate bin/"op-tunnel-server", :executable?
    assert_predicate bin/"op-tunnel-client", :executable?
  end
end
